test push to djs14

diff --git a/addGits b/addGits
--- a/addGits
+++ b/addGits
@@ -2,6 +2,13 @@ echo "added gits"
 function gits() {
     git pull
     git add .
+    
+    # Check if commit was made successfully before proceeding
     git commit -m "$1"
-    git push
+    if [ $? -eq 0 ]; then
+        echo "Commit successful."
+        git push || echo "git push failed."
+    else
+        echo "No changes to commit."
+    fi
 }
